version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mySql_task_management
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: task_management
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
